Skip writing verilator_public for External Module
Yosys can't compile generated Verilog with verilator_debug due to syntax error,

    build/top.v:3: ERROR: syntax error, unexpected ','

because of nested C-style comments for External Modules.

    /* External Modules
    module SB_RAM40_4K (
      input [15:0] MASK/*verilator public*/,